### ISSUE TITLE
Where is the 'allFilename % = Path to H08SST_Jul2019_Jun2020.nc (for training) or to H08SST_Jul2020_Jun2021.nc (for testing)'dataset in your matlab profile

### ISSUE THREAD

**Issue by littlewoodwang** [stephbaker23/bilstm-cloudfill#2]
In the profile'findNeighboursAllImages.m',I may need the allFilename,but you do not commit.Atcually , I really wish you could your CSV profile which you have mentioned.Can you send the CSV to1952342@tongji.edu.cn?Thank you.

**Comment by stephbaker23** [comment]
Hi,

The "allFilename" variable should be updated to contain the path on your computer where you have stored H08SST_Jul2019_Jun2020.nc (if you are creating training data) or H08SST_Jul2020_Jun2021.nc (if you are creating testing data).

I am unable to share the CSV files directly due to storage limitations - the total file size of the CSVs generated using the "findNeighboursAllImages.m" code exceeds 60GB. This is why the "findNeighboursAllImages.m" file has been provided.

Thanks for your interest in our project and data, I hope that this helps.

Cheers,
Steph
