### ISSUE TITLE
findNeighboursAllImages.m

### ISSUE THREAD

**Issue by dubai10086** [stephbaker23/bilstm-cloudfill#3]
None

**Comment by dubai10086** [comment]
I have also tried to change this file myself, but due to not being very familiar with MATLAB, I can only make changes by searching for relevant technologies. However, this code still cannot run properly

**Comment by stephbaker23** [comment]
Hi, 

Lines 3-8 are templates that you will need to complete yourself, with your own filepaths as per the instructions in the comments. Errors with reading the .nc file are likely due to errors in these lines. Please note that proficiency with Matlab is recommended for using this code.

Minor bug fixes have been made to correct a variable name and missing parentheses.

Cheers,
Steph
